<div class="sg-edit-metadata">
  <fieldset class="sg-edit-metadata">
    <legend>Meta-data</legend>
    <label><b>Type: </b><input class="sg-meta" name="meta_format" type="text" maxlength="32" size="32" value="$format$"></input></label>
    <label><b>Title: </b><input class="sg-meta" name="meta_title" type="text" maxlength="128" size="32" value="$title$"></input></label>
    <label><b>Categories: </b><input class="sg-meta" name="meta_categories" type="text" maxlength="128" size="32" value="$categories$"></input></label>
  </fieldset>
</div>
<div class="sg-edit-contents">
  <fieldset class="sg-edit-contents">
    <legend>Contents</legend>
    <label>CKEditor edit area from default template</label>
    <textarea cols="20" class="ckeditor" name="editedText" id="editedText">$contents$</textarea>
    <label>(end edit area from template)</label>
  </fieldset>
</div>
